http:
  port: 3000
admin:
  port: 3004  # Make sure this is not the same as any service ports

apiEndpoints:
  userApi:
    host: '*'
    paths:
      - /customers/*
  productApi:
    host: '*'
    paths:
      - /products/*
  orderApi:
    host: '*'
    paths:
      - /orders/*

serviceEndpoints:
  userService:
    url: 'http://localhost:3002'  # Assuming customer-service is running here
  productService:
    url: 'http://localhost:3001'  # Product service port
  orderService:
    url: 'http://localhost:3003'  # Order service port

policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit

pipelines:
  default:
    apiEndpoints:
      - userApi
      - productApi
      - orderApi
    policies:
      - proxy:
          - action:
              serviceEndpoint: userService
              changeOrigin: true
      - proxy:
          - action:
              serviceEndpoint: productService
              changeOrigin: true
      - proxy:
          - action:
              serviceEndpoint: orderService
              changeOrigin: true
